// <auto-generated />
using System;
using BackEnd.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Migrations
{
    [DbContext(typeof(QuanLyCFDbContext))]
    [Migration("20260615065044_AddCatalog")]
    partial class AddCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackEnd.Domain.Entities.ChiTietCombo", b =>
                {
                    b.Property<int>("MaChiTietCombo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietCombo"));

                    b.Property<int>("MaCombo")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietCombo");

                    b.HasIndex("MaCombo");

                    b.HasIndex("MaSanPham");

                    b.ToTable("ChiTietCombo", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.Combo", b =>
                {
                    b.Property<int>("MaCombo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCombo"));

                    b.Property<decimal>("GiaCombo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCombo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("MaCombo");

                    b.ToTable("Combo", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.DanhMuc", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaDanhMucCha")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ThuTuHienThi")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("MaDanhMuc");

                    b.HasIndex("MaDanhMucCha");

                    b.ToTable("DanhMuc", (string)null);

                    b.HasData(
                        new
                        {
                            MaDanhMuc = 1,
                            TenDanhMuc = "Cà phê",
                            ThuTuHienThi = 1,
                            TrangThaiHoatDong = true
                        },
                        new
                        {
                            MaDanhMuc = 2,
                            TenDanhMuc = "Trà",
                            ThuTuHienThi = 2,
                            TrangThaiHoatDong = true
                        },
                        new
                        {
                            MaDanhMuc = 3,
                            TenDanhMuc = "Đá xay",
                            ThuTuHienThi = 3,
                            TrangThaiHoatDong = true
                        },
                        new
                        {
                            MaDanhMuc = 4,
                            TenDanhMuc = "Bánh",
                            ThuTuHienThi = 4,
                            TrangThaiHoatDong = true
                        },
                        new
                        {
                            MaDanhMuc = 5,
                            TenDanhMuc = "Khác",
                            ThuTuHienThi = 5,
                            TrangThaiHoatDong = true
                        });
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.KichCoSanPham", b =>
                {
                    b.Property<int>("MaKichCo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKichCo"));

                    b.Property<decimal>("GiaCongThem")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<string>("TenKichCo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("MaKichCo");

                    b.HasIndex("MaSanPham");

                    b.ToTable("KichCoSanPham", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("HanTokenKhoiPhuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("KhoaDenKhi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("LuongCoBan")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("MaPinHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoCCCD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoLanDangNhapSai")
                        .HasColumnType("int");

                    b.Property<string>("SoTaiKhoanNganHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenNganHang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenKhoiPhucMatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaNhanVien");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaVaiTro");

                    b.HasIndex("SoCCCD")
                        .IsUnique()
                        .HasFilter("[SoCCCD] IS NOT NULL");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.Quyen", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuyen"));

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nhom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaQuyen");

                    b.HasIndex("MaCode")
                        .IsUnique();

                    b.ToTable("Quyen", (string)null);

                    b.HasData(
                        new
                        {
                            MaQuyen = 1,
                            MaCode = "TAIKHOAN_XEM",
                            Nhom = "TaiKhoan",
                            TenQuyen = "Xem tài khoản"
                        },
                        new
                        {
                            MaQuyen = 2,
                            MaCode = "TAIKHOAN_QUANLY",
                            Nhom = "TaiKhoan",
                            TenQuyen = "Quản lý tài khoản"
                        },
                        new
                        {
                            MaQuyen = 3,
                            MaCode = "SANPHAM_XEM",
                            Nhom = "SanPham",
                            TenQuyen = "Xem sản phẩm"
                        },
                        new
                        {
                            MaQuyen = 4,
                            MaCode = "SANPHAM_QUANLY",
                            Nhom = "SanPham",
                            TenQuyen = "Quản lý sản phẩm"
                        },
                        new
                        {
                            MaQuyen = 5,
                            MaCode = "KHO_XEM",
                            Nhom = "Kho",
                            TenQuyen = "Xem kho"
                        },
                        new
                        {
                            MaQuyen = 6,
                            MaCode = "KHO_QUANLY",
                            Nhom = "Kho",
                            TenQuyen = "Quản lý kho"
                        },
                        new
                        {
                            MaQuyen = 7,
                            MaCode = "DONHANG_XEM",
                            Nhom = "DonHang",
                            TenQuyen = "Xem đơn hàng"
                        },
                        new
                        {
                            MaQuyen = 8,
                            MaCode = "DONHANG_XULY",
                            Nhom = "DonHang",
                            TenQuyen = "Xử lý đơn hàng"
                        },
                        new
                        {
                            MaQuyen = 9,
                            MaCode = "BEP_XEM",
                            Nhom = "Bep",
                            TenQuyen = "Màn hình bếp"
                        },
                        new
                        {
                            MaQuyen = 10,
                            MaCode = "THANHTOAN",
                            Nhom = "ThanhToan",
                            TenQuyen = "Thanh toán"
                        },
                        new
                        {
                            MaQuyen = 11,
                            MaCode = "KHACHHANG_XEM",
                            Nhom = "KhachHang",
                            TenQuyen = "Xem khách hàng"
                        },
                        new
                        {
                            MaQuyen = 12,
                            MaCode = "KHACHHANG_QUANLY",
                            Nhom = "KhachHang",
                            TenQuyen = "Quản lý khách hàng"
                        },
                        new
                        {
                            MaQuyen = 13,
                            MaCode = "NHANSU_XEM",
                            Nhom = "NhanSu",
                            TenQuyen = "Xem nhân sự"
                        },
                        new
                        {
                            MaQuyen = 14,
                            MaCode = "NHANSU_QUANLY",
                            Nhom = "NhanSu",
                            TenQuyen = "Quản lý nhân sự"
                        },
                        new
                        {
                            MaQuyen = 15,
                            MaCode = "BAOCAO_XEM",
                            Nhom = "BaoCao",
                            TenQuyen = "Xem báo cáo"
                        },
                        new
                        {
                            MaQuyen = 16,
                            MaCode = "CAIDAT_QUANLY",
                            Nhom = "CaiDat",
                            TenQuyen = "Quản lý cài đặt"
                        });
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("MaRefreshToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaRefreshToken"));

                    b.Property<DateTime>("HetHan")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianThuHoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaRefreshToken");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("Token");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.SanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSanPham"));

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("GiaVonDuKien")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KieuMon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LaMonNoiBat")
                        .HasColumnType("bit");

                    b.Property<int?>("LuongCalo")
                        .HasColumnType("int");

                    b.Property<int?>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<string>("MaVach_SKU")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ThoiGianChuanBiPhut")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThaiBan")
                        .HasColumnType("bit");

                    b.HasKey("MaSanPham");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex("MaVach_SKU")
                        .IsUnique()
                        .HasFilter("[MaVach_SKU] IS NOT NULL");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<bool>("LaVaiTroHeThong")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVaiTro");

                    b.HasIndex("TenVaiTro")
                        .IsUnique();

                    b.ToTable("VaiTro", (string)null);

                    b.HasData(
                        new
                        {
                            MaVaiTro = 1,
                            LaVaiTroHeThong = true,
                            MoTa = "Toàn quyền hệ thống",
                            TenVaiTro = "Quản lý"
                        },
                        new
                        {
                            MaVaiTro = 2,
                            LaVaiTroHeThong = true,
                            MoTa = "Bếp, đơn hàng, xem kho",
                            TenVaiTro = "Pha chế"
                        },
                        new
                        {
                            MaVaiTro = 3,
                            LaVaiTroHeThong = true,
                            MoTa = "Bán hàng, thu ngân, hoá đơn",
                            TenVaiTro = "Thu ngân"
                        },
                        new
                        {
                            MaVaiTro = 4,
                            LaVaiTroHeThong = true,
                            MoTa = "Đơn hàng, bàn, phục vụ",
                            TenVaiTro = "Phục vụ"
                        },
                        new
                        {
                            MaVaiTro = 5,
                            LaVaiTroHeThong = true,
                            MoTa = "Màn hình bếp",
                            TenVaiTro = "Bếp"
                        });
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.VaiTroQuyen", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<int>("MaQuyen")
                        .HasColumnType("int");

                    b.HasKey("MaVaiTro", "MaQuyen");

                    b.HasIndex("MaQuyen");

                    b.ToTable("VaiTro_Quyen", (string)null);

                    b.HasData(
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 1
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 2
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 3
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 4
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 5
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 6
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 7
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 8
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 9
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 10
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 11
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 12
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 13
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 14
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 15
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 16
                        },
                        new
                        {
                            MaVaiTro = 2,
                            MaQuyen = 3
                        },
                        new
                        {
                            MaVaiTro = 2,
                            MaQuyen = 5
                        },
                        new
                        {
                            MaVaiTro = 2,
                            MaQuyen = 7
                        },
                        new
                        {
                            MaVaiTro = 2,
                            MaQuyen = 8
                        },
                        new
                        {
                            MaVaiTro = 2,
                            MaQuyen = 9
                        },
                        new
                        {
                            MaVaiTro = 3,
                            MaQuyen = 3
                        },
                        new
                        {
                            MaVaiTro = 3,
                            MaQuyen = 7
                        },
                        new
                        {
                            MaVaiTro = 3,
                            MaQuyen = 8
                        },
                        new
                        {
                            MaVaiTro = 3,
                            MaQuyen = 10
                        },
                        new
                        {
                            MaVaiTro = 3,
                            MaQuyen = 11
                        },
                        new
                        {
                            MaVaiTro = 4,
                            MaQuyen = 3
                        },
                        new
                        {
                            MaVaiTro = 4,
                            MaQuyen = 7
                        },
                        new
                        {
                            MaVaiTro = 4,
                            MaQuyen = 8
                        },
                        new
                        {
                            MaVaiTro = 5,
                            MaQuyen = 9
                        },
                        new
                        {
                            MaVaiTro = 5,
                            MaQuyen = 7
                        });
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.ChiTietCombo", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.Combo", "Combo")
                        .WithMany("ChiTiets")
                        .HasForeignKey("MaCombo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Domain.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.DanhMuc", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.DanhMuc", "DanhMucCha")
                        .WithMany("DanhMucCon")
                        .HasForeignKey("MaDanhMucCha")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DanhMucCha");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.KichCoSanPham", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.SanPham", "SanPham")
                        .WithMany("KichCos")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.NhanVien", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.VaiTro", "VaiTro")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.SanPham", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.VaiTroQuyen", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.Quyen", "Quyen")
                        .WithMany("VaiTroQuyens")
                        .HasForeignKey("MaQuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Domain.Entities.VaiTro", "VaiTro")
                        .WithMany("VaiTroQuyens")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quyen");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.Combo", b =>
                {
                    b.Navigation("ChiTiets");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.DanhMuc", b =>
                {
                    b.Navigation("DanhMucCon");

                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.NhanVien", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.Quyen", b =>
                {
                    b.Navigation("VaiTroQuyens");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.SanPham", b =>
                {
                    b.Navigation("KichCos");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.VaiTro", b =>
                {
                    b.Navigation("NhanViens");

                    b.Navigation("VaiTroQuyens");
                });
#pragma warning restore 612, 618
        }
    }
}
