// <auto-generated />
using System;
using BackEnd.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Migrations
{
    [DbContext(typeof(QuanLyCFDbContext))]
    [Migration("20260616032059_AddTableMerge")]
    partial class AddTableMerge
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackEnd.Domain.Entities.Ban", b =>
                {
                    b.Property<int>("MaBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBan"));

                    b.Property<int?>("MaBanChinh")
                        .HasColumnType("int");

                    b.Property<int>("MaKhuVuc")
                        .HasColumnType("int");

                    b.Property<string>("MaQRHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenBan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaBan");

                    b.HasIndex("MaBanChinh");

                    b.HasIndex("MaKhuVuc");

                    b.HasIndex("MaQRHash")
                        .IsUnique();

                    b.HasIndex("TenBan")
                        .IsUnique();

                    b.ToTable("Ban", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.BangLuong", b =>
                {
                    b.Property<int>("MaBangLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBangLuong"));

                    b.Property<string>("Ky")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<decimal>("LuongTheoGio")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<decimal>("Phat")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("PhuCap")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("SoGioOT")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("SoGioThuong")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("SoNgayPhep")
                        .HasColumnType("decimal(5,1)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ThucLanh")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("Thuong")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaBangLuong");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("BangLuong", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.CaLamViec", b =>
                {
                    b.Property<int>("MaCa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCa"));

                    b.Property<TimeOnly>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<string>("TenCa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("MaCa");

                    b.ToTable("CaLamViec", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.CaiDatHeThong", b =>
                {
                    b.Property<int>("MaCaiDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCaiDat"));

                    b.Property<string>("GiaTriCaiDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhoaCaiDat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhomCaiDat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.HasKey("MaCaiDat");

                    b.HasIndex("KhoaCaiDat")
                        .IsUnique();

                    b.ToTable("CaiDatHeThong", (string)null);

                    b.HasData(
                        new
                        {
                            MaCaiDat = 1,
                            GiaTriCaiDat = "BrewManager Coffee",
                            KhoaCaiDat = "TEN_QUAN",
                            MoTa = "Tên quán",
                            NhomCaiDat = "CHUNG",
                            ThoiGianCapNhat = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaCaiDat = 2,
                            GiaTriCaiDat = "",
                            KhoaCaiDat = "DIA_CHI",
                            MoTa = "Địa chỉ quán",
                            NhomCaiDat = "CHUNG",
                            ThoiGianCapNhat = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaCaiDat = 3,
                            GiaTriCaiDat = "8",
                            KhoaCaiDat = "THUE_VAT_MAC_DINH",
                            MoTa = "Thuế VAT mặc định (%)",
                            NhomCaiDat = "THANH_TOAN",
                            ThoiGianCapNhat = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaCaiDat = 4,
                            GiaTriCaiDat = "0",
                            KhoaCaiDat = "PHI_DICH_VU",
                            MoTa = "Phí dịch vụ mặc định (đ)",
                            NhomCaiDat = "THANH_TOAN",
                            ThoiGianCapNhat = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaCaiDat = 5,
                            GiaTriCaiDat = "1",
                            KhoaCaiDat = "TY_LE_TICH_DIEM",
                            MoTa = "Số điểm cho mỗi 1.000đ",
                            NhomCaiDat = "TICH_DIEM",
                            ThoiGianCapNhat = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.ChamCong", b =>
                {
                    b.Property<int>("MaChamCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChamCong"));

                    b.Property<string>("AnhRa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnhVao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LamThemGioPhut")
                        .HasColumnType("int");

                    b.Property<int?>("MaCa")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int>("SoPhutDiTre")
                        .HasColumnType("int");

                    b.Property<int>("SoPhutVeSom")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianRa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianVao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaChamCong");

                    b.HasIndex("MaCa");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("ChamCong", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.ChiTietCombo", b =>
                {
                    b.Property<int>("MaChiTietCombo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietCombo"));

                    b.Property<int>("MaCombo")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietCombo");

                    b.HasIndex("MaCombo");

                    b.HasIndex("MaSanPham");

                    b.ToTable("ChiTietCombo", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<bool>("BaoHetNguyenLieu")
                        .HasColumnType("bit");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("GhiChuMon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaCombo")
                        .HasColumnType("int");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaKichCo")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhanVienPhaChe")
                        .HasColumnType("int");

                    b.Property<int?>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("ThoiGianBaoBep")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianLamXong")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TienGiamGia")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TrangThaiBep")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaCombo");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaKichCo");

                    b.HasIndex("MaNhanVienPhaChe");

                    b.HasIndex("MaSanPham");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.ChiTietPhieuKho", b =>
                {
                    b.Property<int>("MaChiTietPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietPhieu"));

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("LyDoLech")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaNguyenLieu")
                        .HasColumnType("int");

                    b.Property<int>("MaPhieu")
                        .HasColumnType("int");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal?>("SoLuongThucTe")
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("MaChiTietPhieu");

                    b.HasIndex("MaNguyenLieu");

                    b.HasIndex("MaPhieu");

                    b.ToTable("ChiTietPhieuKho", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.Combo", b =>
                {
                    b.Property<int>("MaCombo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCombo"));

                    b.Property<decimal>("GiaCombo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCombo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("MaCombo");

                    b.ToTable("Combo", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<string>("BinhLuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiemSo")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnhDinhKem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<string>("PhanHoiTuQuanLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TrangThaiHienThi")
                        .HasColumnType("bit");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("DanhGia", null, t =>
                        {
                            t.HasCheckConstraint("CK_DanhGia_DiemSo", "[DiemSo] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.DanhMuc", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaDanhMucCha")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ThuTuHienThi")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("MaDanhMuc");

                    b.HasIndex("MaDanhMucCha");

                    b.ToTable("DanhMuc", (string)null);

                    b.HasData(
                        new
                        {
                            MaDanhMuc = 1,
                            TenDanhMuc = "Cà phê",
                            ThuTuHienThi = 1,
                            TrangThaiHoatDong = true
                        },
                        new
                        {
                            MaDanhMuc = 2,
                            TenDanhMuc = "Trà",
                            ThuTuHienThi = 2,
                            TrangThaiHoatDong = true
                        },
                        new
                        {
                            MaDanhMuc = 3,
                            TenDanhMuc = "Đá xay",
                            ThuTuHienThi = 3,
                            TrangThaiHoatDong = true
                        },
                        new
                        {
                            MaDanhMuc = 4,
                            TenDanhMuc = "Bánh",
                            ThuTuHienThi = 4,
                            TrangThaiHoatDong = true
                        },
                        new
                        {
                            MaDanhMuc = 5,
                            TenDanhMuc = "Khác",
                            ThuTuHienThi = 5,
                            TrangThaiHoatDong = true
                        });
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonHang"));

                    b.Property<string>("GhiChuDonHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiDonHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LyDoHuy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaBan")
                        .HasColumnType("int");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaKhuyenMai")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<decimal>("PhiDichVu")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ThueVAT")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TienGiamGia")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TongTienHang")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TrangThaiDon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDonHang");

                    b.HasIndex("MaBan");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaKhuyenMai");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.DonTuNhanVien", b =>
                {
                    b.Property<int>("MaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDon"));

                    b.Property<string>("LoaiDon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaNguoiDuyet")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("ThoiGianLienQuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDon");

                    b.HasIndex("MaNguoiDuyet");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("DonTuNhanVien", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.DongTien", b =>
                {
                    b.Property<int>("MaDongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDongTien"));

                    b.Property<string>("ChungTuDinhKem")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiGiaoDich")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaNhanVienGhiNhan")
                        .HasColumnType("int");

                    b.Property<int?>("MaThamChieu")
                        .HasColumnType("int");

                    b.Property<string>("NguoiNopNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhomGiaoDich")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaDongTien");

                    b.HasIndex("MaNhanVienGhiNhan");

                    b.ToTable("DongTien", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhanVienThuNgan")
                        .HasColumnType("int");

                    b.Property<string>("MaSoThueXuatHD")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SoTienKhachTra")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("ThoiGianThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TienThoiLai")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TongThanhTien")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaDonHang")
                        .IsUnique();

                    b.HasIndex("MaNhanVienThuNgan");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChuKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HangThanhVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LanGheThamCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTienDaTieu")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.KhuVucBan", b =>
                {
                    b.Property<int>("MaKhuVuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhuVuc"));

                    b.Property<decimal>("PhuThu")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TenKhuVuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKhuVuc");

                    b.ToTable("KhuVucBan", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.KhuyenMai", b =>
                {
                    b.Property<int>("MaKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhuyenMai"));

                    b.Property<decimal?>("DonToiThieu")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("GiaTriGiam")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("GiamToiDa")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiGiamGia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaGiamGia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongDaDung")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongGioiHan")
                        .HasColumnType("int");

                    b.Property<string>("TenChuongTrinh")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("MaKhuyenMai");

                    b.HasIndex("MaGiamGia")
                        .IsUnique()
                        .HasFilter("[MaGiamGia] IS NOT NULL");

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.KichCoSanPham", b =>
                {
                    b.Property<int>("MaKichCo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKichCo"));

                    b.Property<decimal>("GiaCongThem")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<string>("TenKichCo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("MaKichCo");

                    b.HasIndex("MaSanPham");

                    b.ToTable("KichCoSanPham", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.LichSuChatbot", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<string>("IntentContext")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<string>("PhanHoiBot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhienChat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TinNhanKhach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLichSu");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("LichSuChatbot", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.LichSuDiem", b =>
                {
                    b.Property<int>("MaLichSuDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSuDiem"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiBienDong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("SoDiem")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLichSuDiem");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("LichSuDiem", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.NguyenLieu", b =>
                {
                    b.Property<int>("MaNguyenLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguyenLieu"));

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("GiaVonTrungBinh")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("HanSuDungNgay")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaVach_SKU")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("MucTonToiDa")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal?>("MucTonToiThieu")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("SoLuongTon")
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("TenNguyenLieu")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaNguyenLieu");

                    b.HasIndex("MaVach_SKU")
                        .IsUnique()
                        .HasFilter("[MaVach_SKU] IS NOT NULL");

                    b.ToTable("NguyenLieu", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.NhaCungCap", b =>
                {
                    b.Property<int>("MaNhaCungCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhaCungCap"));

                    b.Property<decimal>("CongNoHienTai")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaSoThue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NguoiLienHe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SoTaiKhoan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenNganHang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaNhaCungCap");

                    b.ToTable("NhaCungCap", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("HanTokenKhoiPhuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("KhoaDenKhi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("LuongCoBan")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("MaPinHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoCCCD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoLanDangNhapSai")
                        .HasColumnType("int");

                    b.Property<string>("SoTaiKhoanNganHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenNganHang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenKhoiPhucMatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaNhanVien");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaVaiTro");

                    b.HasIndex("SoCCCD")
                        .IsUnique()
                        .HasFilter("[SoCCCD] IS NOT NULL");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.NhatKyHeThong", b =>
                {
                    b.Property<int>("MaNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhatKy"));

                    b.Property<string>("DiaChiIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DuLieuCu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuLieuMoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThietBi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaNhatKy");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("NhatKyHeThong", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.PhanCaLamViec", b =>
                {
                    b.Property<int>("MaPhanCa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanCa"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaCa")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateOnly>("NgayLamViec")
                        .HasColumnType("date");

                    b.HasKey("MaPhanCa");

                    b.HasIndex("MaCa");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("PhanCaLamViec", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.PhanThuong", b =>
                {
                    b.Property<int>("MaPhanThuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanThuong"));

                    b.Property<int>("DiemCanDoi")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhanThuong")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("MaPhanThuong");

                    b.ToTable("PhanThuong", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.PhieuKho", b =>
                {
                    b.Property<int>("MaPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieu"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiPhieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaNhaCungCap")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TienDaThanhToan")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("TongTienHang")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThaiThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPhieu");

                    b.HasIndex("MaNhaCungCap");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("PhieuKho", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.Quyen", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuyen"));

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nhom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaQuyen");

                    b.HasIndex("MaCode")
                        .IsUnique();

                    b.ToTable("Quyen", (string)null);

                    b.HasData(
                        new
                        {
                            MaQuyen = 1,
                            MaCode = "TAIKHOAN_XEM",
                            Nhom = "TaiKhoan",
                            TenQuyen = "Xem tài khoản"
                        },
                        new
                        {
                            MaQuyen = 2,
                            MaCode = "TAIKHOAN_QUANLY",
                            Nhom = "TaiKhoan",
                            TenQuyen = "Quản lý tài khoản"
                        },
                        new
                        {
                            MaQuyen = 3,
                            MaCode = "SANPHAM_XEM",
                            Nhom = "SanPham",
                            TenQuyen = "Xem sản phẩm"
                        },
                        new
                        {
                            MaQuyen = 4,
                            MaCode = "SANPHAM_QUANLY",
                            Nhom = "SanPham",
                            TenQuyen = "Quản lý sản phẩm"
                        },
                        new
                        {
                            MaQuyen = 5,
                            MaCode = "KHO_XEM",
                            Nhom = "Kho",
                            TenQuyen = "Xem kho"
                        },
                        new
                        {
                            MaQuyen = 6,
                            MaCode = "KHO_QUANLY",
                            Nhom = "Kho",
                            TenQuyen = "Quản lý kho"
                        },
                        new
                        {
                            MaQuyen = 7,
                            MaCode = "DONHANG_XEM",
                            Nhom = "DonHang",
                            TenQuyen = "Xem đơn hàng"
                        },
                        new
                        {
                            MaQuyen = 8,
                            MaCode = "DONHANG_XULY",
                            Nhom = "DonHang",
                            TenQuyen = "Xử lý đơn hàng"
                        },
                        new
                        {
                            MaQuyen = 9,
                            MaCode = "BEP_XEM",
                            Nhom = "Bep",
                            TenQuyen = "Màn hình bếp"
                        },
                        new
                        {
                            MaQuyen = 10,
                            MaCode = "THANHTOAN",
                            Nhom = "ThanhToan",
                            TenQuyen = "Thanh toán"
                        },
                        new
                        {
                            MaQuyen = 11,
                            MaCode = "KHACHHANG_XEM",
                            Nhom = "KhachHang",
                            TenQuyen = "Xem khách hàng"
                        },
                        new
                        {
                            MaQuyen = 12,
                            MaCode = "KHACHHANG_QUANLY",
                            Nhom = "KhachHang",
                            TenQuyen = "Quản lý khách hàng"
                        },
                        new
                        {
                            MaQuyen = 13,
                            MaCode = "NHANSU_XEM",
                            Nhom = "NhanSu",
                            TenQuyen = "Xem nhân sự"
                        },
                        new
                        {
                            MaQuyen = 14,
                            MaCode = "NHANSU_QUANLY",
                            Nhom = "NhanSu",
                            TenQuyen = "Quản lý nhân sự"
                        },
                        new
                        {
                            MaQuyen = 15,
                            MaCode = "BAOCAO_XEM",
                            Nhom = "BaoCao",
                            TenQuyen = "Xem báo cáo"
                        },
                        new
                        {
                            MaQuyen = 16,
                            MaCode = "CAIDAT_QUANLY",
                            Nhom = "CaiDat",
                            TenQuyen = "Quản lý cài đặt"
                        },
                        new
                        {
                            MaQuyen = 17,
                            MaCode = "BAN_XEM",
                            Nhom = "Ban",
                            TenQuyen = "Xem bàn"
                        },
                        new
                        {
                            MaQuyen = 18,
                            MaCode = "BAN_QUANLY",
                            Nhom = "Ban",
                            TenQuyen = "Quản lý bàn"
                        });
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("MaRefreshToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaRefreshToken"));

                    b.Property<DateTime>("HetHan")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianThuHoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaRefreshToken");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("Token");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.SanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSanPham"));

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("GiaVonDuKien")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KieuMon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LaMonNoiBat")
                        .HasColumnType("bit");

                    b.Property<int?>("LuongCalo")
                        .HasColumnType("int");

                    b.Property<int?>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<string>("MaVach_SKU")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ThoiGianChuanBiPhut")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThaiBan")
                        .HasColumnType("bit");

                    b.HasKey("MaSanPham");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex("MaVach_SKU")
                        .IsUnique()
                        .HasFilter("[MaVach_SKU] IS NOT NULL");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.ThanhToanChiTiet", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<string>("MaGiaoDichCong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("ThoiGianThanhToan")
                        .HasColumnType("datetime2");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaHoaDon");

                    b.ToTable("ThanhToanChiTiet", (string)null);
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<bool>("LaVaiTroHeThong")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVaiTro");

                    b.HasIndex("TenVaiTro")
                        .IsUnique();

                    b.ToTable("VaiTro", (string)null);

                    b.HasData(
                        new
                        {
                            MaVaiTro = 1,
                            LaVaiTroHeThong = true,
                            MoTa = "Toàn quyền hệ thống",
                            TenVaiTro = "Quản lý"
                        },
                        new
                        {
                            MaVaiTro = 2,
                            LaVaiTroHeThong = true,
                            MoTa = "Bếp, đơn hàng, xem kho",
                            TenVaiTro = "Pha chế"
                        },
                        new
                        {
                            MaVaiTro = 3,
                            LaVaiTroHeThong = true,
                            MoTa = "Bán hàng, thu ngân, hoá đơn",
                            TenVaiTro = "Thu ngân"
                        },
                        new
                        {
                            MaVaiTro = 4,
                            LaVaiTroHeThong = true,
                            MoTa = "Đơn hàng, bàn, phục vụ",
                            TenVaiTro = "Phục vụ"
                        },
                        new
                        {
                            MaVaiTro = 5,
                            LaVaiTroHeThong = true,
                            MoTa = "Màn hình bếp",
                            TenVaiTro = "Bếp"
                        });
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.VaiTroQuyen", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<int>("MaQuyen")
                        .HasColumnType("int");

                    b.HasKey("MaVaiTro", "MaQuyen");

                    b.HasIndex("MaQuyen");

                    b.ToTable("VaiTro_Quyen", (string)null);

                    b.HasData(
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 1
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 2
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 3
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 4
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 5
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 6
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 7
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 8
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 9
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 10
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 11
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 12
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 13
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 14
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 15
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 16
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 17
                        },
                        new
                        {
                            MaVaiTro = 1,
                            MaQuyen = 18
                        },
                        new
                        {
                            MaVaiTro = 2,
                            MaQuyen = 3
                        },
                        new
                        {
                            MaVaiTro = 2,
                            MaQuyen = 5
                        },
                        new
                        {
                            MaVaiTro = 2,
                            MaQuyen = 7
                        },
                        new
                        {
                            MaVaiTro = 2,
                            MaQuyen = 8
                        },
                        new
                        {
                            MaVaiTro = 2,
                            MaQuyen = 9
                        },
                        new
                        {
                            MaVaiTro = 3,
                            MaQuyen = 3
                        },
                        new
                        {
                            MaVaiTro = 3,
                            MaQuyen = 7
                        },
                        new
                        {
                            MaVaiTro = 3,
                            MaQuyen = 8
                        },
                        new
                        {
                            MaVaiTro = 3,
                            MaQuyen = 10
                        },
                        new
                        {
                            MaVaiTro = 3,
                            MaQuyen = 11
                        },
                        new
                        {
                            MaVaiTro = 3,
                            MaQuyen = 17
                        },
                        new
                        {
                            MaVaiTro = 4,
                            MaQuyen = 3
                        },
                        new
                        {
                            MaVaiTro = 4,
                            MaQuyen = 7
                        },
                        new
                        {
                            MaVaiTro = 4,
                            MaQuyen = 8
                        },
                        new
                        {
                            MaVaiTro = 4,
                            MaQuyen = 17
                        },
                        new
                        {
                            MaVaiTro = 5,
                            MaQuyen = 9
                        },
                        new
                        {
                            MaVaiTro = 5,
                            MaQuyen = 7
                        });
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.Ban", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.Ban", "BanChinh")
                        .WithMany()
                        .HasForeignKey("MaBanChinh")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BackEnd.Domain.Entities.KhuVucBan", "KhuVuc")
                        .WithMany("Bans")
                        .HasForeignKey("MaKhuVuc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BanChinh");

                    b.Navigation("KhuVuc");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.BangLuong", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.ChamCong", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.CaLamViec", "Ca")
                        .WithMany()
                        .HasForeignKey("MaCa")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BackEnd.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ca");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.ChiTietCombo", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.Combo", "Combo")
                        .WithMany("ChiTiets")
                        .HasForeignKey("MaCombo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Domain.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.ChiTietDonHang", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.Combo", "Combo")
                        .WithMany()
                        .HasForeignKey("MaCombo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BackEnd.Domain.Entities.DonHang", "DonHang")
                        .WithMany("ChiTiets")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Domain.Entities.KichCoSanPham", "KichCo")
                        .WithMany()
                        .HasForeignKey("MaKichCo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BackEnd.Domain.Entities.NhanVien", "NhanVienPhaChe")
                        .WithMany()
                        .HasForeignKey("MaNhanVienPhaChe")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BackEnd.Domain.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Combo");

                    b.Navigation("DonHang");

                    b.Navigation("KichCo");

                    b.Navigation("NhanVienPhaChe");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.ChiTietPhieuKho", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.NguyenLieu", "NguyenLieu")
                        .WithMany("ChiTietPhieuKhos")
                        .HasForeignKey("MaNguyenLieu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackEnd.Domain.Entities.PhieuKho", "PhieuKho")
                        .WithMany("ChiTiets")
                        .HasForeignKey("MaPhieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguyenLieu");

                    b.Navigation("PhieuKho");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.DanhGia", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BackEnd.Domain.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.DanhMuc", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.DanhMuc", "DanhMucCha")
                        .WithMany("DanhMucCon")
                        .HasForeignKey("MaDanhMucCha")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DanhMucCha");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.DonHang", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.Ban", "Ban")
                        .WithMany()
                        .HasForeignKey("MaBan")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BackEnd.Domain.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BackEnd.Domain.Entities.KhuyenMai", "KhuyenMai")
                        .WithMany()
                        .HasForeignKey("MaKhuyenMai")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BackEnd.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ban");

                    b.Navigation("KhachHang");

                    b.Navigation("KhuyenMai");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.DonTuNhanVien", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.NhanVien", null)
                        .WithMany()
                        .HasForeignKey("MaNguoiDuyet")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BackEnd.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.DongTien", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.NhanVien", "NhanVienGhiNhan")
                        .WithMany()
                        .HasForeignKey("MaNhanVienGhiNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVienGhiNhan");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.HoaDon", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.DonHang", "DonHang")
                        .WithOne()
                        .HasForeignKey("BackEnd.Domain.Entities.HoaDon", "MaDonHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackEnd.Domain.Entities.NhanVien", "NhanVienThuNgan")
                        .WithMany()
                        .HasForeignKey("MaNhanVienThuNgan")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DonHang");

                    b.Navigation("NhanVienThuNgan");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.KichCoSanPham", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.SanPham", "SanPham")
                        .WithMany("KichCos")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.LichSuChatbot", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.LichSuDiem", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BackEnd.Domain.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.NhanVien", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.VaiTro", "VaiTro")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.NhatKyHeThong", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.PhanCaLamViec", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.CaLamViec", "Ca")
                        .WithMany()
                        .HasForeignKey("MaCa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackEnd.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ca");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.PhieuKho", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.NhaCungCap", "NhaCungCap")
                        .WithMany("PhieuKhos")
                        .HasForeignKey("MaNhaCungCap")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BackEnd.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.NhanVien", "NhanVien")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.SanPham", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.ThanhToanChiTiet", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.HoaDon", "HoaDon")
                        .WithMany("ChiTietThanhToans")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.VaiTroQuyen", b =>
                {
                    b.HasOne("BackEnd.Domain.Entities.Quyen", "Quyen")
                        .WithMany("VaiTroQuyens")
                        .HasForeignKey("MaQuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Domain.Entities.VaiTro", "VaiTro")
                        .WithMany("VaiTroQuyens")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quyen");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.Combo", b =>
                {
                    b.Navigation("ChiTiets");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.DanhMuc", b =>
                {
                    b.Navigation("DanhMucCon");

                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.DonHang", b =>
                {
                    b.Navigation("ChiTiets");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.HoaDon", b =>
                {
                    b.Navigation("ChiTietThanhToans");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.KhuVucBan", b =>
                {
                    b.Navigation("Bans");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.NguyenLieu", b =>
                {
                    b.Navigation("ChiTietPhieuKhos");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.NhaCungCap", b =>
                {
                    b.Navigation("PhieuKhos");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.NhanVien", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.PhieuKho", b =>
                {
                    b.Navigation("ChiTiets");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.Quyen", b =>
                {
                    b.Navigation("VaiTroQuyens");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.SanPham", b =>
                {
                    b.Navigation("KichCos");
                });

            modelBuilder.Entity("BackEnd.Domain.Entities.VaiTro", b =>
                {
                    b.Navigation("NhanViens");

                    b.Navigation("VaiTroQuyens");
                });
#pragma warning restore 612, 618
        }
    }
}
